Params:
  Avatar: "static/avatar.png"
  Name: "Victoria Cheng"
  Headline: "Software Developer (Platform & Backend) | Go, Python, Kubernetes | Observability & GitOps | Prev @ Shopify"

  Socials:
    - Platform: "GitHub"
      Icon: "static/icons/github.svg"
      URL: "https://github.com/victoriacheng15"
    - Platform: "LinkedIn"
      Icon: "static/icons/linkedin.svg"
      URL: "https://linkedin.com/in/victoriacheng15"
    - Platform: "YouTube"
      Icon: "static/icons/youtube.svg"
      URL: "https://www.youtube.com/@victoriacheng15"
    - Platform: "Buy Me a Coffee"
      Icon: "static/icons/buymeacoffee.svg"
      URL: "https://buymeacoffee.com/victoriacheng15"

  Links:
    - Name: "🐧 Personal Site"
      URL: "https://victoriacheng15.vercel.app/"
    - Name: "👋 About Me"
      URL: "https://victoriacheng15.vercel.app/about"
    - Name: "⚡ Life Lately"
      URL: "https://victoriacheng15.vercel.app/now"
    - Name: "🛠️ Engineering Logs"
      URL: "https://victoriacheng15.vercel.app/tags/retrospective"